import { Rubik } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import "../../public/css/all.css"

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Rizen Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"
          async
        ></script>
      </head>
      <body className={`${rubik.variable} font-rubik bg-light`}>
        <NavBar />
        <main className="font-rubik flex min-h-screen flex-col px-24 mt-10">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
