import Footer from "@/components/Footer/Footer";
import SideRoute from "@/components/SideRoute/SideRoute";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Rizen Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"
          async
        ></script>
      </head>
      <body 
      className={`${rubik.variable} font-rubik bg-black relative`}>
        <SideRoute/>
        <main className="font-rubik flex min-h-screen flex-col px-24 mt-10">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
